# Generated by Django 3.0.8 on 2020-07-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20200712_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcategory',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
