# Generated by Django 3.0.8 on 2020-07-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20200712_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billcategory',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
