# Generated by Django 3.0.8 on 2020-07-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20200712_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='endless',
            field=models.BooleanField(default=False),
        ),
    ]
