# Generated by Django 3.0.8 on 2020-07-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_bill_endless'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
