# Generated by Django 3.0.8 on 2020-07-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_bill_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='status',
        ),
    ]
