# Generated by Django 3.0.8 on 2020-07-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_auto_20200712_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='attachment',
        ),
    ]
